// @ts-check
/** FR docs (partial tree); order synced from sidebars.js (English).
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "Accueil" },
		{
			type: "category",
			label: "Services",
			collapsible: false,
			items: [{ type: "doc", id: "smartenroll/smartenroll-api-companion", label: "SmartEnroll — Guide API" }],
		},
		{
			type: "category",
			label: "Identité",
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 Citoyen argentin (DNI)", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 Argentine — identité étendue" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 Citoyen bolivien (CI)", key: "identity-bolivia" },
				{ type: "doc", id: "identity/identity-brazil", label: "🇧🇷 Brazil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 Canada — Permis (CB et Ontario)", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 Citoyen chilien (RUN)", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 Chili — Contribuable (RUT)", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 Chili — Validation de document d'identité", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity-validation/colombia/colombia-identity-documents-guide", label: "🇨🇴 Colombie — Guide documents d'identité" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 Colombie — CNI étendu" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 Colombie — Certificat Registraduría" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 Colombie — Citoyen par nom (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 Colombie — Citoyen via Registraduría (SCCRC)" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 Colombie — Registre civil par serial" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 Colombie — Registre civil de mariage" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 Colombie — CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 Colombie — PEP" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 Colombie — PPT" },
				{ type: "doc", id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons", label: "🇨🇴 Colombie — PEP (AML)" },
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 Situation militaire" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 Citoyen costaricien (CCCR)", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 Costa Rica — Lieu de vote" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 Citoyen équatorien (CCEC)", key: "identity-ecuador" },
				{ type: "doc", id: "identity/honduras/votacion", label: "🇭🇳 Honduras — Lieu de vote" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 Citoyen mexicain", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇫🇷 Mexique — Validation INE" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇫🇷 Mexique — OCR INE" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 Citoyen panaméen (CCPA)", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 Citoyen paraguayen (CIC)", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 Pérou — Citoyen (DNI)", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 Pérou — CE étranger" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 Pérou — DNI (données étendues)" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 Citoyen espagnol" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 Citoyen vénézuélien (CCVE)" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 Venezuela — Cédula d'étranger (CEVE)" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 Géolocalisation IP", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "Entreprises (KYB)",
			collapsible: false,
			items: [
				{ type: "doc", id: "business-validation/argentina", label: "🇦🇷 Entreprise argentine (CUIT)", key: "business-argentina" },
				{ type: "doc", id: "business-validation/business-validation-brazil", label: "🇧🇷 Brazil", key: "business-brazil" },
				{ type: "doc", id: "business-validation/canada", label: "🇨🇦 Vérification d'entreprise au Canada", key: "business-canada" },
				{ type: "doc", id: "business-validation/chilean", label: "🇨🇱 Chili — Entreprise (RUT)" },
				{ type: "doc", id: "business-validation/colombia-dian-verification", label: "🇨🇴 Colombie — Vérification DIAN" },
				{ type: "doc", id: "business-validation/colombia-legal-invoicer-verification", label: "🇨🇴 Colombie — Facturier légal" },
				{ type: "doc", id: "business-validation/business-validation-colombia-rues-v3", label: "🇨🇴 Colombie — Consultation RUES (v3)" },
				{ type: "doc", id: "business-validation/rues-complete-v3", label: "🇨🇴 Colombie — RUES dossier complet" },
				{ type: "doc", id: "business-validation/costa-rica", label: "🇨🇷 Entreprise costaricienne (NITE)", key: "business-costa-rica" },
				{ type: "doc", id: "business-validation/ecuador", label: "🇪🇨 Équateur — Entreprise (RUCEC)", key: "business-ecuador" },
				{ type: "doc", id: "business-validation/mexico", label: "🇲🇽 Vérification d'entreprise au Mexique", key: "business-mexico" },
				{ type: "doc", id: "business-validation/panama", label: "🇵🇦 Entreprise panaméenne (RUC)", key: "business-panama" },
				{ type: "doc", id: "business-validation/paraguay", label: "🇵🇾 Entreprise paraguayenne (RUC)", key: "business-paraguay" },
				{ type: "doc", id: "business-validation/peru", label: "🇵🇪 Pérou — Entreprise (RUC)", key: "business-peru" },
				{ type: "doc", id: "business-validation/spain", label: "🇪🇸 Espagne — Entreprise (CIF/NIF)" },
			],
		},
		{
			type: "category",
			label: "Permis de conduire",
			collapsible: false,
			items: [
				{ type: "doc", id: "driver-validation/chile-driver-license", label: "🇨🇱 Chili — Permis de conduire" },
				{ type: "doc", id: "driver-validation/peru-driver-license", label: "🇵🇪 Pérou — Permis de conduire" },
				{ type: "doc", id: "driver-validation/ontario-driver-license", label: "🇨🇦 Ontario — Permis de conduire" },
			],
		},
		{
			type: "category",
			label: "Validation véhicules",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/argentina", label: "Aperçu", key: "vehicle-argentina-overview" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-vehicle-v3", label: "Véhicule v3" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-traffic-infractions", label: "Buenos Aires - Infractions routières" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-technical-inspection", label: "Buenos Aires - Contrôle technique" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-rto", label: "RTO" },
					],
				},
				{ type: "doc", id: "vehicle-validation/bolivia", label: "🇧🇴 Bolivie — Informations véhicule", key: "vehicle-bolivia" },
				{ type: "doc", id: "vehicle-validation/vehicle-validation-brazil", label: "🇧🇷 Brazil", key: "vehicle-brazil" },
				{ type: "doc", id: "vehicle-validation/chile", label: "🇨🇱 Chili — Véhicule (plaque)", key: "vehicle-chile" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-transport-vehicle", label: "🇨🇱 Chili — Transport public", key: "vehicle-chile-transport-vehicle" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-technical-review", label: "🇨🇱 Chili — Contrôle technique", key: "vehicle-chile-vehicle-technical-review" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap", label: "🇨🇱 Chili — SOAP véhicule", key: "vehicle-chile-vehicle-soap" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap-plate", label: "🇨🇱 Chili — SOAP véhicule (par plaque)", key: "vehicle-chile-vehicle-soap-plate" },
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxes", label: "🇨🇴 Bogotá — taxe véhicule" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-fines", label: "🇨🇴 Bogotá — amendes véhicule" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-medellin-vehicle-fines", label: "🇨🇴 Medellín - Amendes" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-accidentality", label: "🇨🇴 Bogotá — accidents" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-pico-y-placa", label: "🇨🇴 Bogotá — Pico y Placa" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-plate", label: "🇨🇴 Bogotá — taxi par plaque" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-control-card", label: "🇨🇴 Bogotá - taxi par carte de contrôle" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-values-by-plate", label: "🇨🇴 Fasecolda — valeur par plaque" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-vehicle-by-code", label: "🇨🇴 Fasecolda — valeur par code" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-claims-verification", label: "🇨🇴 Fasecolda — sinistres" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-drivers-license", label: "🇨🇴 RUNT — Permis" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate", label: "🇨🇴 RUNT — véhicule par plaque (complet)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate-simplified", label: "🇨🇴 RUNT — véhicule par plaque (simplifié)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehiculo", label: "🇨🇴 RUNT — véhicule (base)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-vin", label: "🇨🇴 RUNT — par NIV" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-fines", label: "🇨🇴 SIMIT - Amendes" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-comparendo-details", label: "🇨🇴 SIMIT - Détail comparendo" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-agreements", label: "🇨🇴 SIMIT - Accords de paiement" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-resolutions", label: "🇨🇴 SIMIT - Résolutions" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-suspensiones", label: "🇨🇴 SIMIT — Suspensions" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-document", label: "🇨🇴 SIMIT - Requête générale par pièce d'identité" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-plate", label: "🇨🇴 SIMIT - Requête générale par plaque" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-sisconmp-trainings", label: "🇨🇴 SISCONMP — formation transport" },
					],
				},
				{ type: "doc", id: "vehicle-validation/costa-rica", label: "🇨🇷 Costa Rica — Véhicule par plaque", key: "vehicle-costa-rica" },
				{ type: "doc", id: "vehicle-validation/canada/ontario-plate", label: "🇨🇦 Canada — Expiration plaque Ontario", key: "vehicle-canada-ontario-plate" },
				{ type: "doc", id: "vehicle-validation/ecuador", label: "🇪🇨 Équateur — Amendes véhicule", key: "vehicle-ecuador" },
				{ type: "doc", id: "vehicle-validation/paraguay", label: "🇵🇾 Paraguay — Informations véhicule", key: "vehicle-paraguay" },
				{ type: "doc", id: "vehicle-validation/spain", label: "🇪🇸 Espagne", key: "vehicle-spain" },
				{
					type: "category",
					label: "🇵🇪 Peru",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/peru", label: "🇵🇪 Pérou — Véhicules", key: "vehicle-peru-overview" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-information", label: "🇵🇪 Pérou — Véhicule par plaque" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-insurance", label: "🇵🇪 Pérou — Assurance SOAT" },
					],
				},
			],
		},
		{
			type: "category",
			label: "ANTÉCÉDENTS",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 Brésil", key: "background-check-brazil" },
				{ type: "doc", id: "background-check/argentina-certificate-verify", label: "🇦🇷 Casier judiciaire" },
				{ type: "doc", id: "background-check/chile-certificate-verify", label: "🇨🇱 Registro Civil" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 Contrats publics" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 Mesures correctives (RNMC)" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 Contraloría" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 Discipline (Procuraduría)" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
		{
			type: "category",
			label: "Certificats",
			collapsible: false,
			items: [
				{ type: "doc", id: "certificates/certificates-colombia-ministerio-trabajo-v3", label: "🇨🇴 Ministère du Travail (v3)" },
				{ type: "doc", id: "certificates/certificates-sena-certificates", label: "🇨🇴 Certificats SENA" },
			],
		},
		{
			type: "category",
			label: "VOTE",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/voting", label: "🇨🇴 Colombie — Lieu de vote (Registraduría)" },
				{ type: "doc", id: "legal/epic-eci", label: "🇮🇳 Inde — Recherche de nom EPIC (Voter ID)" },
				{ type: "doc", id: "legal/voting-eci-epic", label: "🇮🇳 Inde — Lieu de vote EPIC" },
			],
		},
		{
			type: "category",
			label: "RESSOURCES",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "Validations téléphoniques",
					collapsible: true,
					items: [
						"resources/phone-validations/phone-validations",
						"resources/phone-validations/the-phone-validation-object",
						"resources/phone-validations/create-a-manual-phone-validation",
						"resources/phone-validations/create-a-phone-validation",
						"resources/phone-validations/retrieve-a-phone-validation",
						"resources/phone-validations/list-all-phone-validations",
						"resources/phone-validations/validate-a-phone-validation",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/privacy-policy", label: "legal/privacy-policy" },
				{ type: "doc", id: "legal/terms-and-conditions", label: "legal/terms-and-conditions" },
				{ type: "doc", id: "legal/service-level-agreement", label: "legal/service-level-agreement" },
				{ type: "doc", id: "legal/verifik-for-enterprises-hub-eng", label: "legal/verifik-for-enterprises-hub-eng" },
				{ type: "doc", id: "legal/smartcheck-terms-and-conditions-of-use", label: "legal/smartcheck-terms-and-conditions-of-use" },
			],
		},
	],
};

export default sidebars;
