// @ts-check
/** JA docs (partial tree); order synced from sidebars.js (English).
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "ホーム" },
		{
			type: "category",
			label: "サービス",
			collapsible: false,
			items: [{ type: "doc", id: "smartenroll/smartenroll-api-companion", label: "SmartEnroll API コンパニオン" }],
		},
		{
			type: "category",
			label: "本人確認",
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 アルゼンチン — 国民身分証", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 アルゼンチン — 拡張本人確認" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 ボリビア国民（CI）", key: "identity-bolivia" },
				{ type: "doc", id: "identity/identity-brazil", label: "🇧🇷 Brazil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 カナダ — 運転免許（BC・オンタリオ）", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 チリ国民（RUN）", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 チリ — 納税者（RUT）", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 チリ — 身分証の有効性確認", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity-validation/colombia/colombia-identity-documents-guide", label: "🇨🇴 コロンビア身分証ガイド" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 国民ID（拡張）" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 選挙管理庁 有効性証明" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 コロンビア — 氏名で市民照会 (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 コロンビア — Registraduría（SCCRC）市民照会" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 コロンビア — シリアルで民事登録" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 コロンビア — 婚姻民事登録" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 外国人 CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 PEP（特別滞在）" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 PPT（一時保護）" },
				{ type: "doc", id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons", label: "🇨🇴 PEP 検索（AML）" },
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 兵役状況" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 コスタリカ国民（CCCR）", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 コスタリカ — 投票所" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 エクアドル国民（CCEC）", key: "identity-ecuador" },
				{ type: "doc", id: "identity/honduras/votacion", label: "🇭🇳 ホンジュラス — 投票所" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 メキシコ国民", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇲🇽 メキシコ — INE 検証" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇲🇽 メキシコ — INE OCR" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 パナマ国民（CCPA）", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 パラグアイ国民（CIC）", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 ペルー国民（DNI）", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 ペルー外国人CE" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 ペルーDNI（拡張）" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 スペイン国民" },
				{ type: "doc", id: "identity/united-states", label: "🇺🇸 アメリカ — SSN", key: "identity-united-states" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 ベネズエラ国民（CCVE）" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 ベネズエラ — 外国人身分証（CEVE）" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 IP ジオロケーション", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "法人(KYB)",
			collapsible: false,
			items: [
				{ type: "doc", id: "business-validation/argentina", label: "🇦🇷 アルゼンチン — 法人検証", key: "business-argentina" },
				{ type: "doc", id: "business-validation/bolivia", label: "🇧🇴 Bolivia", key: "business-bolivia" },
				{ type: "doc", id: "business-validation/business-validation-brazil", label: "🇧🇷 Brazil", key: "business-brazil" },
				{ type: "doc", id: "business-validation/canada", label: "🇨🇦 カナダ法人検証", key: "business-canada" },
				{ type: "doc", id: "business-validation/chilean", label: "🇨🇱 チリ — 企業（RUT）" },
				{ type: "doc", id: "business-validation/colombia-dian-verification", label: "🇨🇴 コロンビア — DIAN 税務確認" },
				{ type: "doc", id: "business-validation/colombia-legal-invoicer-verification", label: "🇨🇴 コロンビア — DIAN 法定請求者" },
				{ type: "doc", id: "business-validation/business-validation-colombia-rues-v3", label: "🇨🇴 コロンビア — RUES 企業照会 (v3)" },
				{ type: "doc", id: "business-validation/rues-complete-v3", label: "🇨🇴 コロンビア — RUES 企業フル" },
				{ type: "doc", id: "business-validation/costa-rica", label: "🇨🇷 コスタリカ法人（NITE）", key: "business-costa-rica" },
				{ type: "doc", id: "business-validation/ecuador", label: "🇪🇨 エクアドル法人（RUCEC）", key: "business-ecuador" },
				{ type: "doc", id: "business-validation/mexico", label: "🇲🇽 メキシコ法人検証", key: "business-mexico" },
				{ type: "doc", id: "business-validation/panama", label: "🇵🇦 パナマ企業（RUC）", key: "business-panama" },
				{ type: "doc", id: "business-validation/paraguay", label: "🇵🇾 パラグアイ企業（RUC）", key: "business-paraguay" },
				{ type: "doc", id: "business-validation/peru", label: "🇵🇪 ペルー企業（RUC）", key: "business-peru" },
				{ type: "doc", id: "business-validation/spain", label: "🇪🇸 スペイン — 企業（CIF/NIF）" },
				{ type: "doc", id: "business-validation/united-states", label: "🇺🇸 アメリカ法人（SEC EDGAR）", key: "business-united-states" },
			],
		},
		{
			type: "category",
			label: "運転免許",
			collapsible: false,
			items: [
				{ type: "doc", id: "driver-validation/chile-driver-license", label: "🇨🇱 チリ — 運転免許" },
				{ type: "doc", id: "driver-validation/peru-driver-license", label: "🇵🇪 ペルー — 運転免許" },
				{ type: "doc", id: "driver-validation/florida-driver-license", label: "🇺🇸 フロリダ州 — 運転免許" },
				{ type: "doc", id: "driver-validation/kansas-driver-license", label: "🇺🇸 カンザス州 — 運転免許" },
				{ type: "doc", id: "driver-validation/ontario-driver-license", label: "🇨🇦 オンタリオ — 運転免許" },
			],
		},
		{
			type: "category",
			label: "車両検証",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/argentina", label: "概要", key: "vehicle-argentina-overview" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-vehicle-v3", label: "車両 v3" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-traffic-infractions", label: "ブエノスアイレス - 交通違反" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-technical-inspection", label: "ブエノスアイレス - 技術検査" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-rto", label: "RTO" },
					],
				},
				{ type: "doc", id: "vehicle-validation/bolivia", label: "🇧🇴 ボリビア — 車両情報", key: "vehicle-bolivia" },
				{ type: "doc", id: "vehicle-validation/vehicle-validation-brazil", label: "🇧🇷 Brazil", key: "vehicle-brazil" },
				{ type: "doc", id: "vehicle-validation/chile", label: "🇨🇱 チリ — 車両（ナンバー）", key: "vehicle-chile" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-transport-vehicle", label: "🇨🇱 チリ — 公共交通車両", key: "vehicle-chile-transport-vehicle" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-technical-review", label: "🇨🇱 チリ — 車両技術検査", key: "vehicle-chile-vehicle-technical-review" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap", label: "🇨🇱 チリ — 車両 SOAP", key: "vehicle-chile-vehicle-soap" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap-plate", label: "🇨🇱 チリ — 車両 SOAP（番号のみ）", key: "vehicle-chile-vehicle-soap-plate" },
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxes", label: "🇨🇴 ボゴタ — 車両税" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-fines", label: "🇨🇴 ボゴタ — 車両反則金" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-medellin-vehicle-fines", label: "🇨🇴 メデジン - 交通違反" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-accidentality", label: "🇨🇴 ボゴタ — 交通事故履歴" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-pico-y-placa", label: "🇨🇴 ボゴタ — ピコ・イ・プラカ" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-plate", label: "🇨🇴 ボゴタ — タクシー（プレート）" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-control-card", label: "🇨🇴 ボゴタ - タクシー（管理カード）" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-values-by-plate", label: "🇨🇴 Fasecolda — ナンバー別車両価格" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-vehicle-by-code", label: "🇨🇴 Fasecolda — コード別車両価格" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-claims-verification", label: "🇨🇴 Fasecolda — 保険請求履歴" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-drivers-license", label: "🇨🇴 RUNT — 運転免許" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate", label: "🇨🇴 RUNT — 車両（ナンバー・詳細）" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate-simplified", label: "🇨🇴 RUNT — 車両（ナンバー・簡易）" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehiculo", label: "🇨🇴 RUNT — 車両(基本)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-vin", label: "🇨🇴 RUNT — VIN" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-fines", label: "🇨🇴 SIMIT - 反則金" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-comparendo-details", label: "🇨🇴 SIMIT - 違反切符詳細" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-agreements", label: "🇨🇴 SIMIT - 分割払い合意" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-resolutions", label: "🇨🇴 SIMIT - 決議" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-suspensiones", label: "🇨🇴 SIMIT — 免許停止" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-document", label: "🇨🇴 SIMIT - 身分証明書による一般照会" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-plate", label: "🇨🇴 SIMIT - ナンバープレートによる一般照会" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-sisconmp-trainings", label: "🇨🇴 SISCONMP — 運送検証" },
					],
				},
				{ type: "doc", id: "vehicle-validation/costa-rica", label: "🇨🇷 コスタリカ — 車両（ナンバー）", key: "vehicle-costa-rica" },
				{ type: "doc", id: "vehicle-validation/canada/ontario-plate", label: "🇨🇦 カナダ — オンタリオ ナンバー有効期限", key: "vehicle-canada-ontario-plate" },
				{ type: "doc", id: "vehicle-validation/ecuador", label: "🇪🇨 エクアドル — 車両罰金", key: "vehicle-ecuador" },
				{ type: "doc", id: "vehicle-validation/paraguay", label: "🇵🇾 パラグアイ — 車両情報", key: "vehicle-paraguay" },
				{ type: "doc", id: "vehicle-validation/spain", label: "🇪🇸 スペイン", key: "vehicle-spain" },
				{
					type: "category",
					label: "🇵🇪 Peru",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/peru", label: "🇵🇪 ペルー — 車両", key: "vehicle-peru-overview" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-information", label: "🇵🇪 ペルー — 車両（ナンバー）" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-insurance", label: "🇵🇪 ペルー — SOAT保険" },
					],
				},
				{
					type: "category",
					label: "🇺🇸 United States",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/united-states/vehicle-by-vin", label: "車両（VIN）", key: "vehicle-united-states" },
					],
				},
			],
		},
		{
			type: "category",
			label: "背景調査",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 ブラジル", key: "background-check-brazil" },
				{ type: "doc", id: "background-check/argentina-certificate-verify", label: "🇦🇷 犯罪歴証明" },
				{ type: "doc", id: "background-check/chile-certificate-verify", label: "🇨🇱 Registro Civil" },
				{ type: "doc", id: "background-check/united-states-passport-entries", label: "🇺🇸 パスポート・米国入出国" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 公共契約" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 是正措置" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 会計検査院証明" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 懲戒記録" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/colombia-sisben-score", label: "🇨🇴 SISBEN" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
		{
			type: "category",
			label: "証明書",
			collapsible: false,
			items: [
				{ type: "doc", id: "certificates/certificates-colombia-ministerio-trabajo-v3", label: "🇨🇴 労働省証明書（v3）" },
				{ type: "doc", id: "certificates/certificates-sena-certificates", label: "🇨🇴 SENA 証明書" },
			],
		},
		{
			type: "category",
			label: "投票",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/voting", label: "🇨🇴 コロンビア — 投票場所（Registraduría）" },
				{ type: "doc", id: "legal/epic-eci", label: "🇮🇳 インド — EPIC（Voter ID）氏名照会" },
				{ type: "doc", id: "legal/voting-eci-epic", label: "🇮🇳 インド — EPIC 投票所・投票場所" },
			],
		},
		{
			type: "category",
			label: "リソース",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "電話認証",
					collapsible: true,
					items: [
						"resources/phone-validations/phone-validations",
						"resources/phone-validations/the-phone-validation-object",
						"resources/phone-validations/create-a-manual-phone-validation",
						"resources/phone-validations/create-a-phone-validation",
						"resources/phone-validations/retrieve-a-phone-validation",
						"resources/phone-validations/list-all-phone-validations",
						"resources/phone-validations/validate-a-phone-validation",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/privacy-policy", label: "legal/privacy-policy" },
				{ type: "doc", id: "legal/terms-and-conditions", label: "legal/terms-and-conditions" },
				{ type: "doc", id: "legal/service-level-agreement", label: "legal/service-level-agreement" },
				{ type: "doc", id: "legal/verifik-for-enterprises-hub-eng", label: "legal/verifik-for-enterprises-hub-eng" },
				{ type: "doc", id: "legal/smartcheck-terms-and-conditions-of-use", label: "legal/smartcheck-terms-and-conditions-of-use" },
			],
		},
	],
};

export default sidebars;
