// @ts-check
/** ZH docs (partial tree); order synced from sidebars.js (English).
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "主页" },
		{
			type: "category",
			label: "服务",
			collapsible: false,
			items: [{ type: "doc", id: "smartenroll/smartenroll-api-companion", label: "SmartEnroll API 指南" }],
		},
		{
			type: "category",
			label: "身份核验",
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 阿根廷公民（DNI）", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 阿根廷 — 扩展身份" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 玻利维亚公民（CI）", key: "identity-bolivia" },
				{ type: "doc", id: "identity/identity-brazil", label: "🇧🇷 Brazil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 加拿大 — 驾驶证（BC 与安大略）", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 智利国民身份证（RUN）", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 智利 — 纳税人（RUT）", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 智利 — 身份证件有效性", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity/colombia", label: "🇨🇴 哥伦比亚公民（CC / PPT）" },
				{ type: "doc", id: "identity-validation/colombia/colombia-identity-documents-guide", label: "🇨🇴 哥伦比亚证件指南" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 国民身份证（扩展）" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 选举机构有效性证明" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 哥伦比亚 — 按姓名查公民 (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 哥伦比亚 — 通过 Registraduría（SCCRC）查询公民" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 哥伦比亚 — 按序列号查民事登记" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 哥伦比亚 — 婚姻民事登记" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 外国人 CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 PEP（特别居留）" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 PPT（临时保护）" },
				{ type: "doc", id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons", label: "🇨🇴 PEP 查询（AML）" },
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 兵役状况" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 哥斯达黎加国民身份证（CCCR）", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 哥斯达黎加 — 投票地点" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 厄瓜多尔公民（CCEC）", key: "identity-ecuador" },
				{ type: "doc", id: "identity/honduras/votacion", label: "🇭🇳 洪都拉斯 — 投票地点" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 墨西哥公民", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇲🇽 墨西哥 — INE 验证" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇲🇽 墨西哥 — INE OCR" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 巴拿马国民身份证（CCPA）", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 巴拉圭公民（CIC）", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 秘鲁公民（DNI）", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 秘鲁外国人 CE" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 秘鲁 DNI（扩展）" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 西班牙公民" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 委内瑞拉国民（CCVE）" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 委内瑞拉 — 外国人身份证（CEVE）" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 IP 地理定位", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "企业(KYB)",
			collapsible: false,
			items: [
				{ type: "doc", id: "business-validation/argentina", label: "🇦🇷 阿根廷企业（CUIT）", key: "business-argentina" },
				{ type: "doc", id: "business-validation/business-validation-brazil", label: "🇧🇷 Brazil", key: "business-brazil" },
				{ type: "doc", id: "business-validation/canada", label: "🇨🇦 加拿大企业核验", key: "business-canada" },
				{ type: "doc", id: "business-validation/chilean", label: "🇨🇱 智利 — 企业（RUT）" },
				{ type: "doc", id: "business-validation/colombia-dian-verification", label: "🇨🇴 DIAN 税务核验" },
				{ type: "doc", id: "business-validation/colombia-legal-invoicer-verification", label: "🇨🇴 法定开票人核验" },
				{ type: "doc", id: "business-validation/business-validation-colombia-rues-v3", label: "🇨🇴 RUES 企业查询 (v3)" },
				{ type: "doc", id: "business-validation/rues-complete-v3", label: "🇨🇴 RUES 完整核验 (v3)" },
				{ type: "doc", id: "business-validation/costa-rica", label: "🇨🇷 哥斯达黎加企业（NITE）", key: "business-costa-rica" },
				{ type: "doc", id: "business-validation/ecuador", label: "🇪🇨 厄瓜多尔企业（RUCEC）", key: "business-ecuador" },
				{ type: "doc", id: "business-validation/mexico", label: "🇲🇽 墨西哥企业核验", key: "business-mexico" },
				{ type: "doc", id: "business-validation/panama", label: "🇵🇦 巴拿马企业（RUC）", key: "business-panama" },
				{ type: "doc", id: "business-validation/paraguay", label: "🇵🇾 巴拉圭企业（RUC）", key: "business-paraguay" },
				{ type: "doc", id: "business-validation/peru", label: "🇵🇪 秘鲁企业（RUC）", key: "business-peru" },
				{ type: "doc", id: "business-validation/spain", label: "🇪🇸 西班牙 — 企业（CIF/NIF）" },
			],
		},
		{
			type: "category",
			label: "驾驶证",
			collapsible: false,
			items: [
				{ type: "doc", id: "driver-validation/chile-driver-license", label: "🇨🇱 智利 — 驾驶证" },
				{ type: "doc", id: "driver-validation/peru-driver-license", label: "🇵🇪 秘鲁 — 驾驶证" },
				{ type: "doc", id: "driver-validation/ontario-driver-license", label: "🇨🇦 安大略 — 驾驶证" },
			],
		},
		{
			type: "category",
			label: "车辆核验",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/argentina", label: "概览", key: "vehicle-argentina-overview" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-vehicle-v3", label: "车辆 v3" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-traffic-infractions", label: "布宜诺斯艾利斯 - 交通违章" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-technical-inspection", label: "布宜诺斯艾利斯 - 技术检验" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-rto", label: "RTO" },
					],
				},
				{ type: "doc", id: "vehicle-validation/bolivia", label: "🇧🇴 玻利维亚 — 车辆信息", key: "vehicle-bolivia" },
				{ type: "doc", id: "vehicle-validation/vehicle-validation-brazil", label: "🇧🇷 Brazil", key: "vehicle-brazil" },
				{ type: "doc", id: "vehicle-validation/chile", label: "🇨🇱 智利 — 车辆（号牌）", key: "vehicle-chile" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-transport-vehicle", label: "🇨🇱 智利 — 公共交通车辆", key: "vehicle-chile-transport-vehicle" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-technical-review", label: "🇨🇱 智利 — 车辆技术检验", key: "vehicle-chile-vehicle-technical-review" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap", label: "🇨🇱 智利 — 车辆 SOAP", key: "vehicle-chile-vehicle-soap" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap-plate", label: "🇨🇱 智利 — 车辆 SOAP（仅车牌）", key: "vehicle-chile-vehicle-soap-plate" },
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxes", label: "🇨🇴 波哥大 — 车辆税费" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-fines", label: "🇨🇴 波哥大 — 车辆罚单" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-medellin-vehicle-fines", label: "🇨🇴 麦德林 - 交通罚单" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-accidentality", label: "🇨🇴 波哥大 — 事故记录" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-pico-y-placa", label: "🇨🇴 波哥大 — Pico y Placa" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-plate", label: "🇨🇴 波哥大 — 出租车（车牌）" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-control-card", label: "🇨🇴 波哥大 - 出租车（控制卡）" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-values-by-plate", label: "🇨🇴 Fasecolda — 按车牌车辆价值" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-vehicle-by-code", label: "🇨🇴 Fasecolda — 按代码车辆价值" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-claims-verification", label: "🇨🇴 Fasecolda — 理赔记录" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-drivers-license", label: "🇨🇴 RUNT — 驾驶证" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate", label: "🇨🇴 RUNT — 按车牌车辆(完整)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate-simplified", label: "🇨🇴 RUNT — 按车牌车辆(简化)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehiculo", label: "🇨🇴 RUNT — 车辆(基本)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-vin", label: "🇨🇴 RUNT — 车辆(VIN)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-fines", label: "🇨🇴 SIMIT - 罚款" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-comparendo-details", label: "🇨🇴 SIMIT - 罚单详情" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-agreements", label: "🇨🇴 SIMIT - 分期付款协议" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-resolutions", label: "🇨🇴 SIMIT - 决议" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-suspensiones", label: "🇨🇴 SIMIT — 驾照停用" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-document", label: "🇨🇴 SIMIT - 按身份证件综合查询" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-plate", label: "🇨🇴 SIMIT - 按车牌综合查询" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-sisconmp-trainings", label: "🇨🇴 SISCONMP — 运输培训核验" },
					],
				},
				{ type: "doc", id: "vehicle-validation/costa-rica", label: "🇨🇷 哥斯达黎加 — 车辆（号牌）", key: "vehicle-costa-rica" },
				{ type: "doc", id: "vehicle-validation/canada/ontario-plate", label: "🇨🇦 加拿大 — 安大略车牌到期", key: "vehicle-canada-ontario-plate" },
				{ type: "doc", id: "vehicle-validation/ecuador", label: "🇪🇨 厄瓜多尔 — 车辆罚单", key: "vehicle-ecuador" },
				{ type: "doc", id: "vehicle-validation/paraguay", label: "🇵🇾 巴拉圭 — 车辆信息", key: "vehicle-paraguay" },
				{ type: "doc", id: "vehicle-validation/spain", label: "🇪🇸 西班牙", key: "vehicle-spain" },
				{
					type: "category",
					label: "🇵🇪 Peru",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/peru", label: "🇵🇪 秘鲁 — 车辆", key: "vehicle-peru-overview" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-information", label: "🇵🇪 秘鲁 — 车辆（号牌）" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-insurance", label: "🇵🇪 秘鲁 — SOAT 保险" },
					],
				},
			],
		},
		{
			type: "category",
			label: "背景调查",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 巴西", key: "background-check-brazil" },
				{ type: "doc", id: "background-check/argentina-certificate-verify", label: "🇦🇷 犯罪记录证明" },
				{ type: "doc", id: "background-check/chile-certificate-verify", label: "🇨🇱 民事登记证明" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 公共合同" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 纠正措施" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 审计署证明" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 纪律处分记录" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/colombia-sisben-score", label: "🇨🇴 SISBEN 分数" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
		{
			type: "category",
			label: "证书",
			collapsible: false,
			items: [
				{ type: "doc", id: "certificates/certificates-colombia-ministerio-trabajo-v3", label: "🇨🇴 劳动部证书 (v3)" },
				{ type: "doc", id: "certificates/certificates-sena-certificates", label: "🇨🇴 SENA 证书" },
			],
		},
		{
			type: "category",
			label: "投票",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/voting", label: "🇨🇴 哥伦比亚 — 投票地点（Registraduría）" },
				{ type: "doc", id: "legal/epic-eci", label: "🇮🇳 印度 — EPIC（选民证）姓名查询" },
				{ type: "doc", id: "legal/voting-eci-epic", label: "🇮🇳 印度 — EPIC 投票站/投票地点" },
			],
		},
		{
			type: "category",
			label: "资源",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "电话验证",
					collapsible: true,
					items: [
						"resources/phone-validations/phone-validations",
						"resources/phone-validations/the-phone-validation-object",
						"resources/phone-validations/create-a-manual-phone-validation",
						"resources/phone-validations/create-a-phone-validation",
						"resources/phone-validations/retrieve-a-phone-validation",
						"resources/phone-validations/list-all-phone-validations",
						"resources/phone-validations/validate-a-phone-validation",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/privacy-policy", label: "legal/privacy-policy" },
				{ type: "doc", id: "legal/terms-and-conditions", label: "legal/terms-and-conditions" },
				{ type: "doc", id: "legal/service-level-agreement", label: "legal/service-level-agreement" },
				{ type: "doc", id: "legal/verifik-for-enterprises-hub-eng", label: "legal/verifik-for-enterprises-hub-eng" },
				{ type: "doc", id: "legal/smartcheck-terms-and-conditions-of-use", label: "legal/smartcheck-terms-and-conditions-of-use" },
			],
		},
	],
};

export default sidebars;
