// @ts-check
/** KO docs (partial tree); order synced from sidebars.js (English).
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "홈" },
		{
			type: "category",
			label: "서비스",
			collapsible: false,
			items: [{ type: "doc", id: "smartenroll/smartenroll-api-companion", label: "SmartEnroll API 가이드" }],
		},
		{
			type: "category",
			label: "신원",
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 아르헨티나 시민(DNI)", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 아르헨티나 — 확장 신원" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 볼리비아 국민(CI)", key: "identity-bolivia" },
				{ type: "doc", id: "identity/identity-brazil", label: "🇧🇷 Brazil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 캐나다 — 운전면허(BC·온타리오)", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 칠레 국민 식별(RUN)", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 칠레 — 납세자(RUT)", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 칠레 — 신분증 유효성 검증", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity-validation/colombia/colombia-identity-documents-guide", label: "🇨🇴 콜롬비아 신분증 가이드" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 국민ID (확장)" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 선거청 유효성 증명" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 콜롬비아 — 이름으로 시민 조회 (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 콜롬비아 — Registraduría(SCCRC) 시민 조회" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 콜롬비아 — 일련번호로 민사 등록" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 콜롬비아 — 혼인 민사 등록" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 외국인 CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 PEP (특별 체류)" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 PPT (임시 보호)" },
				{ type: "doc", id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons", label: "🇨🇴 PEP 조회 (AML)" },
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 군 복무 기록" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 코스타리카 국민 신분증(CCCR)", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 코스타리카 — 투표 장소" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 에콰도르 국민(CCEC)", key: "identity-ecuador" },
				{ type: "doc", id: "identity/honduras/votacion", label: "🇭🇳 온두라스 — 투표 장소" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 멕시코 시민", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇲🇽 멕시코 — INE 검증" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇲🇽 멕시코 — INE OCR" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 파나마 국민 (CCPA)", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 파라과이 국민 (CIC)", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 페루 국민(DNI)", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 페루 외국인 CE" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 페루 DNI(확장)" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 스페인 국민" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 베네수엘라 국민(CCVE)" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 베네수엘라 — 외국인 신분증(CEVE)" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 IP 지리적 위치", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "기업(KYB)",
			collapsible: false,
			items: [
				{ type: "doc", id: "business-validation/argentina", label: "🇦🇷 아르헨티나 기업(CUIT)", key: "business-argentina" },
				{ type: "doc", id: "business-validation/business-validation-brazil", label: "🇧🇷 Brazil", key: "business-brazil" },
				{ type: "doc", id: "business-validation/canada", label: "🇨🇦 캐나다 기업 검증", key: "business-canada" },
				{ type: "doc", id: "business-validation/chilean", label: "🇨🇱 칠레 — 기업(RUT)" },
				{ type: "doc", id: "business-validation/colombia-dian-verification", label: "🇨🇴 콜롬비아 — 세금 정보 확인 (DIAN)" },
				{ type: "doc", id: "business-validation/colombia-legal-invoicer-verification", label: "🇨🇴 콜롬비아 — DIAN 전자 청구" },
				{ type: "doc", id: "business-validation/business-validation-colombia-rues-v3", label: "🇨🇴 콜롬비아 — RUES 기업 조회 (v3)" },
				{ type: "doc", id: "business-validation/rues-complete-v3", label: "🇨🇴 콜롬비아 — RUES 전체 검증" },
				{ type: "doc", id: "business-validation/costa-rica", label: "🇨🇷 코스타리카 기업(NITE)", key: "business-costa-rica" },
				{ type: "doc", id: "business-validation/ecuador", label: "🇪🇨 에콰도르 기업(RUCEC)", key: "business-ecuador" },
				{ type: "doc", id: "business-validation/mexico", label: "🇲🇽 멕시코 기업 검증", key: "business-mexico" },
				{ type: "doc", id: "business-validation/panama", label: "🇵🇦 파나마 기업 (RUC)", key: "business-panama" },
				{ type: "doc", id: "business-validation/paraguay", label: "🇵🇾 파라과이 기업 (RUC)", key: "business-paraguay" },
				{ type: "doc", id: "business-validation/peru", label: "🇵🇪 페루 기업(RUC)", key: "business-peru" },
				{ type: "doc", id: "business-validation/spain", label: "🇪🇸 스페인 — 기업(CIF/NIF)" },
			],
		},
		{
			type: "category",
			label: "운전면허",
			collapsible: false,
			items: [
				{ type: "doc", id: "driver-validation/chile-driver-license", label: "🇨🇱 칠레 — 운전면허" },
				{ type: "doc", id: "driver-validation/peru-driver-license", label: "🇵🇪 페루 — 운전면허" },
				{ type: "doc", id: "driver-validation/kansas-driver-license", label: "🇺🇸 캔자스주 — 운전면허" },
				{ type: "doc", id: "driver-validation/ontario-driver-license", label: "🇨🇦 온타리오 — 운전면허" },
			],
		},
		{
			type: "category",
			label: "차량 검증",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/argentina", label: "개요", key: "vehicle-argentina-overview" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-vehicle-v3", label: "차량 v3" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-traffic-infractions", label: "부에노스아이레스 - 교통 위반" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-technical-inspection", label: "부에노스아이레스 - 기술 검사" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-rto", label: "RTO" },
					],
				},
				{ type: "doc", id: "vehicle-validation/bolivia", label: "🇧🇴 볼리비아 — 차량 정보", key: "vehicle-bolivia" },
				{ type: "doc", id: "vehicle-validation/vehicle-validation-brazil", label: "🇧🇷 Brazil", key: "vehicle-brazil" },
				{ type: "doc", id: "vehicle-validation/chile", label: "🇨🇱 칠레 — 차량(번호판)", key: "vehicle-chile" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-transport-vehicle", label: "🇨🇱 칠레 — 대중교통 차량", key: "vehicle-chile-transport-vehicle" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-technical-review", label: "🇨🇱 칠레 — 차량 기술 검사", key: "vehicle-chile-vehicle-technical-review" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap", label: "🇨🇱 칠레 — 차량 SOAP", key: "vehicle-chile-vehicle-soap" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap-plate", label: "🇨🇱 칠레 — 차량 SOAP (번호판)", key: "vehicle-chile-vehicle-soap-plate" },
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxes", label: "🇨🇴 보고타 — 차량세" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-fines", label: "🇨🇴 보고타 — 차량 과태료" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-medellin-vehicle-fines", label: "🇨🇴 메데인 - 교통 벌금" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-accidentality", label: "🇨🇴 보고타 — 사고 이력" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-pico-y-placa", label: "🇨🇴 보고타 — 피코이플라카" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-plate", label: "🇨🇴 보고타 — 택시（번호판）" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-control-card", label: "🇨🇴 보고타 - 택시（관리 카드）" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-values-by-plate", label: "🇨🇴 Fasecolda — 번호판 차량 가치" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-vehicle-by-code", label: "🇨🇴 Fasecolda — 코드별 차량 가치" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-claims-verification", label: "🇨🇴 Fasecolda — 보험 청구" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-drivers-license", label: "🇨🇴 RUNT — 운전면허" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate", label: "🇨🇴 RUNT — 차량 확인" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate-simplified", label: "🇨🇴 RUNT — 차량 확인(간편)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehiculo", label: "🇨🇴 RUNT — 차량 확인(기본)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-vin", label: "🇨🇴 RUNT — VIN 차량 확인" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-fines", label: "🇨🇴 SIMIT - 과태료" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-comparendo-details", label: "🇨🇴 SIMIT - 범칙금 상세" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-agreements", label: "🇨🇴 SIMIT - 분할 납부 합의" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-resolutions", label: "🇨🇴 SIMIT - 결의" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-suspensiones", label: "🇨🇴 SIMIT — 면허 정지" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-document", label: "🇨🇴 SIMIT - 신분증 기반 일반 조회" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-plate", label: "🇨🇴 SIMIT - 번호판 기반 일반 조회" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-sisconmp-trainings", label: "🇨🇴 SISCONMP — 운송 검증" },
					],
				},
				{ type: "doc", id: "vehicle-validation/costa-rica", label: "🇨🇷 코스타리카 — 차량(번호판)", key: "vehicle-costa-rica" },
				{ type: "doc", id: "vehicle-validation/canada/ontario-plate", label: "🇨🇦 캐나다 — 온타리오 번호판 만료", key: "vehicle-canada-ontario-plate" },
				{ type: "doc", id: "vehicle-validation/ecuador", label: "🇪🇨 에콰도르 — 차량 벌금", key: "vehicle-ecuador" },
				{ type: "doc", id: "vehicle-validation/paraguay", label: "🇵🇾 파라과이 — 차량 정보", key: "vehicle-paraguay" },
				{ type: "doc", id: "vehicle-validation/spain", label: "🇪🇸 스페인", key: "vehicle-spain" },
				{
					type: "category",
					label: "🇵🇪 Peru",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/peru", label: "🇵🇪 페루 — 차량", key: "vehicle-peru-overview" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-information", label: "🇵🇪 페루 — 차량(번호판)" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-insurance", label: "🇵🇪 페루 — SOAT 보험" },
					],
				},
			],
		},
		{
			type: "category",
			label: "배경 조회",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 브라질", key: "background-check-brazil" },
				{ type: "doc", id: "background-check/argentina-certificate-verify", label: "🇦🇷 범죄 경력 증명" },
				{ type: "doc", id: "background-check/chile-certificate-verify", label: "🇨🇱 Registro Civil" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 공공 계약" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 시정 조치" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 감사원 증명" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 징계 기록" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
		{
			type: "category",
			label: "증명서",
			collapsible: false,
			items: [
				{ type: "doc", id: "certificates/certificates-colombia-ministerio-trabajo-v3", label: "🇨🇴 노동부 증명서（v3）" },
				{ type: "doc", id: "certificates/certificates-sena-certificates", label: "🇨🇴 SENA 증명서" },
			],
		},
		{
			type: "category",
			label: "투표",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/voting", label: "🇨🇴 콜롬비아 — 투표 장소 (Registraduría)" },
				{ type: "doc", id: "legal/epic-eci", label: "🇮🇳 인도 — EPIC (Voter ID) 이름 조회" },
				{ type: "doc", id: "legal/voting-eci-epic", label: "🇮🇳 인도 — EPIC 투표소/투표 위치" },
			],
		},
		{
			type: "category",
			label: "리소스",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "전화 인증",
					collapsible: true,
					items: [
						"resources/phone-validations/phone-validations",
						"resources/phone-validations/the-phone-validation-object",
						"resources/phone-validations/create-a-manual-phone-validation",
						"resources/phone-validations/create-a-phone-validation",
						"resources/phone-validations/retrieve-a-phone-validation",
						"resources/phone-validations/list-all-phone-validations",
						"resources/phone-validations/validate-a-phone-validation",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/privacy-policy", label: "legal/privacy-policy" },
				{ type: "doc", id: "legal/terms-and-conditions", label: "legal/terms-and-conditions" },
				{ type: "doc", id: "legal/service-level-agreement", label: "legal/service-level-agreement" },
				{ type: "doc", id: "legal/verifik-for-enterprises-hub-eng", label: "legal/verifik-for-enterprises-hub-eng" },
				{ type: "doc", id: "legal/smartcheck-terms-and-conditions-of-use", label: "legal/smartcheck-terms-and-conditions-of-use" },
			],
		},
	],
};

export default sidebars;
