// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Spanish sidebar configuration for Zelf Documentation
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// Spanish sidebar structure
	tutorialSidebar: [
		{
			type: "doc",
			id: "intro",
			label: "Bienvenido a Verifik",
		},
		{
			type: "category",
			label: "AUTENTICACIÓN",
			collapsible: false,
			items: [
				"autenticacion/api-key-acceso-por-email",
				"autenticacion/api-key-acceso-por-telefono",
				"autenticacion/renovar-tu-token-jwt",
				"autenticacion/crear-nuevo-token-y-revocar-tokens-previos",
			],
		},
		{
			type: "category",
			label: "CLIENTES",
			collapsible: false,
			items: ["clients/informacion-cuenta"],
		},
		{
			type: "category",
			label: "SERVICIOS",
			collapsible: false,
			items: [
				"smartcheck/verificacion-inteligente",
				"smartaccess/acceso-inteligente",
				"access/acceso",
				"smartenroll/smartenroll",
				"smartenroll/smartenroll-flujo-kyc",
				"smartenroll/smartenroll-admin-revision-kyc",
				"smartenroll/smartenroll-guia-api",
				"smart-enroll-auto-alojado/smart-enroll-self-hosted",
				"smart-scan/escaneo-inteligente",
			],
		},
		{
			type: "category",
			label: "BIOMETRICS API'S",
			collapsible: false,
			items: [
				"biometrics/deteccion-vitalidad",
				"biometrics/puntaje-vitalidad",
				{
					type: "category",
					label: "Comparación Facial",
					collapsible: true,
					items: ["biometrics/comparar", "biometrics/comparar-en-vivo", "biometrics/comparar-con-deteccion-vitalidad"],
				},
				{
					type: "category",
					label: "Búsqueda Facial",
					collapsible: true,
					items: ["biometrics/buscar", "biometrics/buscar-cara-en-vivo", "biometrics/buscar-usuario-activo", "biometrics/buscar-recortes"],
				},
				{
					type: "category",
					label: "HumanAuthn",
					collapsible: true,
					items: [
						"biometrics/pruebas-faciales-conocimiento-cero-resumen",
						"biometrics/humanauthn-vs-ur-codes",
						"biometrics/pruebas-faciales-conocimiento-cero-encriptar",
						"biometrics/pruebas-faciales-conocimiento-cero-encriptar-codigo-qr",
						"biometrics/pruebas-faciales-conocimiento-cero-desencriptar",
						"biometrics/pruebas-faciales-conocimiento-cero-vista-previa",
					],
				},
			],
		},
		{
			type: "category",
			label: "SCAN DOCS API'S",
			collapsible: false,
			items: ["ocr-engines/escaneo-estudio", "ocr-engines/escaneo-prompt"],
		},
		{
			type: "category",
			label: "VERIFICACIÓN DE IDENTIDAD",
			link: {
				type: "doc",
				id: "identity/verificacion-identidad",
			},
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 Argentina", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 Argentina - Extra" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 Bolivia", key: "identity-bolivia" },
				{ type: "doc", id: "identity/brazil", label: "🇧🇷 Brasil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 Canadá", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 Chile", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 Chile — Contribuyente (RUT)", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 Chile — Validación de documento", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity/colombia", label: "🇨🇴 Ciudadano Colombiano" },
				{
					type: "doc",
					id: "validacion-identidad/colombia/guia-documentos-identidad-colombia",
					label: "🇨🇴 Guía de documentos de identidad",
				},
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 Colombia - ID Completo" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 Colombia - Certificado Registraduría" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 Colombia — Ciudadano por nombre (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 Colombia — Ciudadano vía Registraduría (SCCRC)" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 Colombia — Registro civil por serial" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 Colombia — Registro civil de matrimonio" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 Colombia - CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 Colombia — PEP" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 Colombia - PPT" },
				{
					type: "doc",
					id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons",
					label: "🇨🇴 Colombia — PEP (AML)",
				},
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 Colombia - Situación militar" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 Costa Rica", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 Costa Rica — Lugar de Votación" },
				{ type: "doc", id: "identity/dominican-republic", label: "🇩🇴 República Dominicana", key: "identity-dominican-republic" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 Ecuador", key: "identity-ecuador" },
				{ type: "doc", id: "identity/el-salvador", label: "🇸🇻 El Salvador" },
				{ type: "doc", id: "identity/guatemala", label: "🇬🇹 Guatemala" },
				{ type: "doc", id: "identity/guatemala-extra", label: "🇬🇹 Guatemala - Extra" },
				{ type: "doc", id: "identity/honduras", label: "🇭🇳 Honduras" },
				{ type: "doc", id: "identidad/honduras/votacion", label: "🇭🇳 Honduras — Lugar de Votación" },
				{ type: "doc", id: "identity/india-epic", label: "🇮🇳 India", key: "identity-india-epic" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 México", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇲🇽 México — Validación INE" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇲🇽 México — OCR INE" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 Panamá", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 Paraguay", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 Perú", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 Perú - Cédula de Extranjero" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 Perú - ID Completo" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 Ciudadano Español" },
				{ type: "doc", id: "identity/estados-unidos", label: "🇺🇸 Estados Unidos", key: "identity-estados-unidos" },
				{ type: "doc", id: "identity/uruguay", label: "🇺🇾 Uruguay" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 Venezuela" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 Venezuela - Cédula de Extranjero" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 Consulta de Geoubicación IP", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN EMPRESARIAL",
			link: {
				type: "doc",
				id: "validacion-empresarial/verificacion-empresarial",
			},
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "validacion-empresarial/argentina",
					label: "🇦🇷 Argentina",
					key: "empresarial-argentina",
				},
				{
					type: "doc",
					id: "validacion-empresarial/bolivia",
					label: "🇧🇴 Bolivia",
					key: "empresarial-bolivia",
				},
				{
					type: "doc",
					id: "validacion-empresarial/brazil",
					label: "🇧🇷 Brasil",
					key: "empresarial-brazil",
				},
				{
					type: "doc",
					id: "validacion-empresarial/canada",
					label: "🇨🇦 Canadá",
					key: "empresarial-canada",
				},
				{
					type: "doc",
					id: "validacion-empresarial/chilean",
					label: "🇨🇱 Chile",
					key: "empresarial-chile",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-verificacion-dian",
					label: "🇨🇴 Colombia — Verificación DIAN (NIT)",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-verificacion-facturador-legal",
					label: "🇨🇴 Colombia — Facturación electrónica DIAN",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-rues-v3",
					label: "🇨🇴 Colombia — RUES (v3 básico)",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-validacion-empresarial-rues-completa-v3",
					label: "🇨🇴 Colombia — RUES expediente completo (v3)",
				},
				{
					type: "doc",
					id: "validacion-empresarial/costa-rica-empresarial",
					label: "🇨🇷 Costa Rica",
					key: "empresarial-costa-rica",
				},
				{
					type: "doc",
					id: "validacion-empresarial/ecuador",
					label: "🇪🇨 Ecuador",
					key: "empresarial-ecuador",
				},
				{
					type: "doc",
					id: "validacion-empresarial/mexico",
					label: "🇲🇽 México",
					key: "empresarial-mexico",
				},
				{
					type: "doc",
					id: "validacion-empresarial/panama",
					label: "🇵🇦 Panamá",
					key: "empresarial-panama",
				},
				{
					type: "doc",
					id: "validacion-empresarial/paraguay",
					label: "🇵🇾 Paraguay",
					key: "empresarial-paraguay",
				},
				{
					type: "doc",
					id: "validacion-empresarial/peru",
					label: "🇵🇪 Perú",
					key: "empresarial-peru",
				},
				{
					type: "doc",
					id: "validacion-empresarial/spain",
					label: "🇪🇸 España",
				},
				{
					type: "doc",
					id: "validacion-empresarial/united-states",
					label: "🇺🇸 Estados Unidos",
					key: "empresarial-estados-unidos",
				},
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN DE LICENCIAS DE MANEJO",
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "validaciones-conductores/chile-licencia-conducir",
					label: "🇨🇱 Chile - Licencia de Conducir",
				},
				{
					type: "doc",
					id: "validaciones-conductores/peru-licencia-conducir",
					label: "🇵🇪 Perú - Licencia de Conducir",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-florida",
					label: "🇺🇸 Florida - Licencia de Manejo",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-kansas",
					label: "🇺🇸 Kansas - Licencia de Manejo",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-ontario",
					label: "🇨🇦 Ontario - Licencia de Manejo",
				},
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN DE VEHÍCULOS",
			link: {
				type: "doc",
				id: "validacion-vehiculos/verificacion-vehiculos",
			},
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/argentina",
							label: "Resumen",
							key: "vehiculos-argentina-overview",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/argentina/validacion-vehiculos-argentina-vehicle-v3",
							label: "Vehículo v3",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/argentina/validacion-vehiculos-argentina-buenos-aires-traffic-infractions",
							label: "Buenos Aires - Infracciones de Tránsito",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/argentina/validacion-vehiculos-argentina-buenos-aires-technical-inspection",
							label: "Buenos Aires - Inspección Técnica",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/argentina/validacion-vehiculos-argentina-rto",
							label: "RTO",
						},
					],
				},
				{
					type: "doc",
					id: "validacion-vehiculos/bolivia",
					label: "🇧🇴 Bolivia",
					key: "vehiculos-bolivia",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/brazil",
					label: "🇧🇷 Brasil",
					key: "vehiculos-brazil",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile",
					label: "🇨🇱 Chile",
					key: "vehiculos-chile",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile/validacion-vehiculos-chile-transport-vehicle",
					label: "🇨🇱 Chile - Vehículo de transporte público",
					key: "vehiculos-chile-transport-vehicle",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile/validacion-vehiculos-chile-vehicle-technical-review",
					label: "🇨🇱 Chile - Revisión técnica vehicular",
					key: "vehiculos-chile-vehicle-technical-review",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile/validacion-vehiculos-chile-vehicle-soap",
					label: "🇨🇱 Chile - SOAP vehicular",
					key: "vehiculos-chile-vehicle-soap",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile/validacion-vehiculos-chile-vehicle-soap-plate",
					label: "🇨🇱 Chile - SOAP vehicular (por patente)",
					key: "vehiculos-chile-vehicle-soap-plate",
				},
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/colombia",
							label: "Resumen",
							key: "vehiculos-colombia-resumen",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/impuestos-bogota",
							label: "Impuestos en Bogotá",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/multas-vehiculos-bogota",
							label: "Verificación de Multas de Vehículos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/validacion-vehiculos-colombia-medellin-multas-vehiculo",
							label: "Medellín - Multas de tránsito",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/accidentalidad-vehiculos-bogota",
							label: "Accidentalidad de Vehículos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/pico-y-placa-bogota",
							label: "Pico y Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/taxis-conductores-bogota-por-tarjeta",
							label: "Bogotá - Taxis (por tarjeta)",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/valores-vehiculos-por-placa-fasecolda",
							label: "Valores de Vehículos por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/vehiculo-por-codigo-fasecolda",
							label: "Vehículo por Código",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/verificacion-siniestros-fasecolda",
							label: "Verificación de Siniestros",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/licencia-conducir-runt",
							label: "Licencia de Conducir",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-placa-runt",
							label: "Registros de Vehículos por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-placa-simplificado-runt",
							label: "Registros de Vehículos por Placa (Simplificado)",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/runt-vehiculo",
							label: "RUNT - Vehículo (básico)",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-vin-runt",
							label: "Registros de Vehículos por VIN",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/colombia-runt-soat-rtm",
							label: "RUNT - SOAT y RTM",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/multas-simit",
							label: "SIMIT - Multas",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/validacion-vehiculos-colombia-simit-comparendo-detalles",
							label: "SIMIT - Detalles de comparendo",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/acuerdos-simit",
							label: "SIMIT - Acuerdos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/resoluciones-simit",
							label: "SIMIT - Resoluciones",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/suspensiones-licencia-simit",
							label: "SIMIT - Suspensiones de licencia",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/consulta-general-por-documento-simit",
							label: "Consulta General por Documento",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/consulta-general-por-placa-simit",
							label: "Consulta General por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-entrenamiento-sisconmp",
							label: "Registros de Entrenamiento SISCONMP",
						},
					],
				},
				{
					type: "doc",
					id: "validacion-vehiculos/costa-rica",
					label: "🇨🇷 Costa Rica",
					key: "vehiculos-costa-rica",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/canada/placa-ontario",
					label: "🇨🇦 Canadá - Vencimiento de Placa Ontario",
					key: "vehiculos-canada-placa-ontario",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/ecuador",
					label: "🇪🇨 Ecuador",
					key: "vehiculos-ecuador",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/mexico",
					label: "🇲🇽 México",
					key: "vehiculos-mexico",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/paraguay",
					label: "🇵🇾 Paraguay",
					key: "vehiculos-paraguay",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/spain",
					label: "🇪🇸 España",
					key: "vehiculos-espana",
				},
				{
					type: "category",
					label: "🇵🇪 Perú",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/peru",
							label: "Resumen",
							key: "vehiculos-peru-resumen",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/peru/peru-informacion-vehiculo",
							label: "Información de Vehículo",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/peru/peru-seguro-vehiculo",
							label: "Seguro de Vehículo",
						},
					],
				},
				{
					type: "category",
					label: "🇺🇸 Estados Unidos",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/estados-unidos",
							label: "Vehículo por placa",
							key: "vehiculos-estados-unidos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/estados-unidos-vin",
							label: "Vehículo por VIN",
						},
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFICACIÓN DE ANTECEDENTES",
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-brasil",
					label: "🇧🇷 Brasil - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-estados-unidos-entradas-pasaporte",
					label: "🇺🇸 EE. UU. - Pasaporte y entradas/salidas",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-contratos-publicos",
					label: "🇨🇴 Colombia - Contratos Públicos",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-cumplimiento-policial",
					label: "🇨🇴 Colombia - Cumplimiento Policial",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-contraloria",
					label: "🇨🇴 Colombia - Contraloría",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-argentina-certificado-penal",
					label: "🇦🇷 Argentina - Certificado de Antecedentes Penales",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-chile-certificado-registro-civil",
					label: "🇨🇱 Chile - Certificado Registro Civil",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-procuraduria",
					label: "🇨🇴 Colombia - Procuraduría",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-inpec",
					label: "🇨🇴 Colombia - INPEC",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-sisben",
					label: "🇨🇴 Colombia - SISBEN",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-europol",
					label: "🌐 Europol - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-dea",
					label: "🌐 DEA - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-fbi",
					label: "🌐 FBI - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-interpol",
					label: "🌐 Interpol - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-ofac",
					label: "🌐 OFAC - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-de-antecedentes/internacional/verificacion-antecedentes-onu",
					label: "🌐 ONU - Antecedentes",
				},
			],
		},
		{
			type: "category",
			label: "VOTACIÓN",
			collapsible: false,
			items: [
				"legal/votacion",
				{
					type: "doc",
					id: "legal/epic-eci",
					label: "🇮🇳 India - Consulta de nombre EPIC (Voter ID)",
				},
				{
					type: "doc",
					id: "legal/votacion-eci-epic",
					label: "🇮🇳 India - Ubicación de votación EPIC",
				},
			],
		},
		{
			type: "category",
			label: "SALUD",
			collapsible: false,
			items: ["legal/salud", "legal/colombia-rethus", "legal/verificar-afiliaciones-colombianas"],
		},
		{
			type: "category",
			label: "VERIFICACIONES LEGALES",
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "legal/verificacion-abogados",
					label: "🇨🇴 Verificación de Abogado Colombiano",
				},
				{
					type: "doc",
					id: "legal/procesos-legales-colombianos",
					label: "🇨🇴 Procesos Legales Colombianos",
				},
				{
					type: "doc",
					id: "legal/antecedentes-judiciales-colombia",
					label: "🇨🇴 Colombia — Antecedentes Judiciales",
				},
				{
					type: "doc",
					id: "legal/recuperar-detalles-proceso-legal-por-numero",
					label: "🇨🇴 Detalles de Proceso Legal Colombiano",
				},
				{
					type: "doc",
					id: "legal/certificado-vigencia-profesionales-legales",
					label: "🇨🇴 Vigencia de Profesionales Legales Colombianos",
				},
				{
					type: "doc",
					id: "legal/sigep-servidor-publico-por-numero",
					label: "🇨🇴 Colombia - Consulta de Servidor Público por Número (SIGEP)",
				},
				{
					type: "doc",
					id: "legal/sigep-servidor-publico-por-nombre",
					label: "🇨🇴 Colombia - Consulta de Servidor Público por Nombre (SIGEP)",
				},
			],
		},
		{
			type: "category",
			label: "RECURSOS",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "Proyectos",
					key: "resources-proyectos",
					collapsible: true,
					items: [
						"resources/proyectos/el-objeto-proyecto",
						"resources/proyectos/crear-un-proyecto",
						"resources/proyectos/recuperar-un-proyecto",
						"resources/proyectos/listar-todos-los-proyectos",
						"resources/proyectos/actualizar-un-proyecto",
						"resources/proyectos/eliminar-un-proyecto",
					],
				},
				{
					type: "category",
					label: "Registros de Aplicación",
					collapsible: true,
					items: [
						"resources/registros-aplicacion/registros-aplicacion",
						"resources/registros-aplicacion/el-objeto-registro-aplicacion",
						"resources/registros-aplicacion/crear-un-registro-aplicacion",
						"resources/registros-aplicacion/recuperar-un-registro-aplicacion",
						"resources/registros-aplicacion/listar-todos-los-registros-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-biometrica-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-documento-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-email-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-telefono-registro-aplicacion",
						"resources/registros-aplicacion/validar-una-validacion-email-registro-aplicacion",
						"resources/registros-aplicacion/validar-una-validacion-telefono-registro-aplicacion",
						"resources/registros-aplicacion/sincronizar-estado-registro-aplicacion",
					],
				},
				{
					type: "category",
					label: "Validaciones Biométricas",
					collapsible: true,
					items: [
						"resources/validaciones-biometricas/validaciones-biometricas",
						"resources/validaciones-biometricas/el-objeto-validacion-biometrica",
						"resources/validaciones-biometricas/crear-una-validacion-biometrica",
						"resources/validaciones-biometricas/recuperar-una-validacion-biometrica",
						"resources/validaciones-biometricas/listar-todas-las-validaciones-biometricas",
					],
				},
				{
					type: "category",
					label: "Vivacidad de Documentos",
					collapsible: true,
					items: [
						"resources/vivacidad-documentos/vivacidad-documentos",
						"resources/vivacidad-documentos/el-objeto-vivacidad-documento",
						"resources/vivacidad-documentos/crear-una-vivacidad-documento",
						"resources/vivacidad-documentos/recuperar-una-vivacidad-documento",
						"resources/vivacidad-documentos/listar-todas-las-vivacidades-documentos",
					],
				},
				{
					type: "category",
					label: "Validaciones de Documentos",
					collapsible: true,
					items: [
						"resources/validaciones-documentos/validaciones-documentos",
						"resources/validaciones-documentos/el-objeto-validacion-documento",
						"resources/validaciones-documentos/crear-una-validacion-nombre",
						"resources/validaciones-documentos/recuperar-una-validacion-documento",
						"resources/validaciones-documentos/listar-todas-las-validaciones-documentos",
						"resources/validaciones-documentos/actualizar-una-validacion-documento",
						"resources/validaciones-documentos/eliminar-una-validacion-documento",
					],
				},
				{
					type: "category",
					label: "Validaciones de Email",
					collapsible: true,
					items: [
						"resources/validaciones-email/validaciones-email",
						"resources/validaciones-email/el-objeto-validacion-email",
						"resources/validaciones-email/crear-una-validacion-email",
						"resources/validaciones-email/recuperar-una-validacion-email",
						"resources/validaciones-email/listar-todas-las-validaciones-email",
						"resources/validaciones-email/validar-una-validacion-email",
					],
				},
				{
					type: "category",
					label: "Personas",
					collapsible: true,
					items: [
						"resources/personas/personas",
						"resources/personas/el-objeto-persona",
						"resources/personas/crear-una-persona",
						"resources/personas/recuperar-una-persona",
						"resources/personas/listar-todas-las-personas",
					],
				},
				{
					type: "category",
					label: "Validaciones de Teléfono",
					collapsible: true,
					items: [
						"resources/validaciones-telefono/validaciones-telefono",
						"resources/validaciones-telefono/el-objeto-validacion-telefono",
						"resources/validaciones-telefono/crear-una-validacion-telefono",
						"resources/validaciones-telefono/recuperar-una-validacion-telefono",
						"resources/validaciones-telefono/listar-todas-las-validaciones-telefono",
						"resources/validaciones-telefono/validar-una-validacion-telefono",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
				{
					type: "category",
					label: "Tickets de Soporte",
					collapsible: true,
					items: [
						"resources/tickets-soporte/tickets-soporte",
						"resources/tickets-soporte/el-objeto-ticket-soporte",
						"resources/tickets-soporte/crear-un-ticket-soporte",
						"resources/tickets-soporte/recuperar-un-ticket-soporte",
						"resources/tickets-soporte/listar-todos-los-tickets-soporte",
					],
				},
				{
					type: "category",
					label: "Webhooks",
					collapsible: true,
					items: [
						"resources/webhooks/webhooks",
						"resources/webhooks/integracion-webhook",
						"resources/webhooks/smart-enroll-kyc-webhooks",
						"resources/webhooks/eventos-soportados",
						"resources/webhooks/el-objeto-webhook",
						"resources/webhooks/crear-un-webhook",
						"resources/webhooks/recuperar-un-webhook",
						"resources/webhooks/listar-todos-los-webhooks",
						"resources/webhooks/actualizar-un-webhook",
						"resources/webhooks/eliminar-un-webhook",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				"legal/politica-privacidad",
				"legal/terminos-y-condiciones",
				"legal/acuerdo-de-niveles-de-servicio",
				"legal/verifik-for-enterprises-hub-esp",
				"legal/smartcheck-terminos-y-condiciones-de-uso",
			],
		},
		{
			type: "category",
			label: "HOJA DE RUTA",
			collapsible: false,
			items: ["hoja-ruta/roadmap-2026"],
		},
	],
};

module.exports = sidebars;
