// @ts-check
/** PT docs (partial tree); order synced from sidebars.js (English).
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "Início" },
		{
			type: "category",
			label: "Serviços",
			collapsible: false,
			items: [{ type: "doc", id: "smartenroll/smartenroll-api-companion", label: "SmartEnroll — Guia da API" }],
		},
		{
			type: "category",
			label: "Biometria",
			collapsible: false,
			items: [{ type: "doc", id: "biometrics/face-image-requirements", label: "Requisitos da imagem facial" }],
		},
		{
			type: "category",
			label: "Identidade",
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 Cidadão argentino (DNI)", key: "identity-argentina" },
				{ type: "doc", id: "identity/argentina-extra", label: "🇦🇷 Argentina — identidade ampliada" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 Cidadão boliviano (CI)", key: "identity-bolivia" },
				{ type: "doc", id: "identity/identity-brazil", label: "🇧🇷 Brazil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 Canadá — Habilitação (BC e ON)", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 Cidadão chileno (RUN)", key: "identity-chile" },
				{ type: "doc", id: "identity/chile-taxpayer", label: "🇨🇱 Chile — Contribuinte (RUT)", key: "identity-chile-taxpayer" },
				{ type: "doc", id: "identity/chile-validate-documents", label: "🇨🇱 Chile — Validação de documento de identidade", key: "identity-chile-validate-documents" },
				{ type: "doc", id: "identity-validation/colombia/colombia-identity-documents-guide", label: "🇨🇴 Colômbia — Guia de documentos" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 Colômbia — RG estendido" },
				{ type: "doc", id: "identity/colombia-registraduria-certificate", label: "🇨🇴 Colômbia — Certificado Registraduría" },
				{
					type: "doc",
					id: "identity-validation/colombia/colombian-citizen-by-name",
					label: "🇨🇴 Colômbia — Cidadão por nome (SCCRC)",
				},
				{ type: "doc", id: "identity/colombia-cedula-registraduria", label: "🇨🇴 Colômbia — Cidadão via Registraduría (SCCRC)" },
				{ type: "doc", id: "identity/colombia-registraduria-serial", label: "🇨🇴 Colômbia — Registro civil por serial" },
				{ type: "doc", id: "identity/colombia-registraduria-matrimonio", label: "🇨🇴 Colômbia — Registro civil de casamento" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 Colômbia — CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 Colômbia — PEP" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 Colômbia — PPT" },
				{ type: "doc", id: "identity-validation/colombia/identity-validation-colombia-colombian-politically-exposed-persons", label: "🇨🇴 Colômbia — PEP (AML)" },
				{ type: "doc", id: "identity/colombia-situacion-militar", label: "🇨🇴 Situação militar" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 Cidadão costa-riquenho (CCCR)", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/costa-rica/votacion", label: "🇨🇷 Costa Rica — Local de votação" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 Cidadão equatoriano (CCEC)", key: "identity-ecuador" },
				{ type: "doc", id: "identity/honduras/votacion", label: "🇭🇳 Honduras — Local de votação" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 Cidadão mexicano", key: "identity-mexico" },
				{ type: "doc", id: "identity/mexico-ine", label: "🇲🇽 México — Validação INE" },
				{ type: "doc", id: "identity/mexico-ine-ocr", label: "🇲🇽 México — OCR INE" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 Cidadão panamenho (CCPA)", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 Cidadão paraguaio (CIC)", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 Peru — Cidadão (DNI)", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 Peru — Cédula de estrangeiro (CE)" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 Peru — DNI (dados estendidos)" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 Cidadão espanhol" },
				{ type: "doc", id: "identity/united-states", label: "🇺🇸 EUA — SSN (Social Security Number)", key: "identity-united-states" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 Cidadão venezuelano (CCVE)" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 Venezuela — Cédula de estrangeiro (CEVE)" },
				{ type: "doc", id: "identity/identity-ip-lookup", label: "🌐 Geolocalização IP", key: "identity-ip-lookup" },
			],
		},
		{
			type: "category",
			label: "Empresas (KYB)",
			collapsible: false,
			items: [
				{ type: "doc", id: "business-validation/argentina", label: "🇦🇷 Empresa argentina (CUIT)", key: "business-argentina" },
				{ type: "doc", id: "business-validation/business-validation-brazil", label: "🇧🇷 Brazil", key: "business-brazil" },
				{ type: "doc", id: "business-validation/canada", label: "🇨🇦 Verificação de empresas no Canadá", key: "business-canada" },
				{ type: "doc", id: "business-validation/chilean", label: "🇨🇱 Chile — Empresa (RUT)" },
				{ type: "doc", id: "business-validation/colombia-dian-verification", label: "🇨🇴 Colômbia — Verificação DIAN" },
				{ type: "doc", id: "business-validation/colombia-legal-invoicer-verification", label: "🇨🇴 Colômbia — Faturador legal" },
				{ type: "doc", id: "business-validation/business-validation-colombia-rues-v3", label: "🇨🇴 Colômbia — Consulta RUES (v3)" },
				{ type: "doc", id: "business-validation/rues-complete-v3", label: "🇨🇴 Colômbia — RUES empresa completa" },
				{ type: "doc", id: "business-validation/costa-rica", label: "🇨🇷 Empresa na Costa Rica (NITE)", key: "business-costa-rica" },
				{ type: "doc", id: "business-validation/ecuador", label: "🇪🇨 Equador — Empresa (RUCEC)", key: "business-ecuador" },
				{ type: "doc", id: "business-validation/mexico", label: "🇲🇽 Verificação de empresas no México", key: "business-mexico" },
				{ type: "doc", id: "business-validation/panama", label: "🇵🇦 Empresa panamenha (RUC)", key: "business-panama" },
				{ type: "doc", id: "business-validation/paraguay", label: "🇵🇾 Empresa paraguaia (RUC)", key: "business-paraguay" },
				{ type: "doc", id: "business-validation/peru", label: "🇵🇪 Peru — Empresa (RUC)", key: "business-peru" },
				{ type: "doc", id: "business-validation/spain", label: "🇪🇸 Espanha — Empresa (CIF/NIF)" },
				{ type: "doc", id: "business-validation/united-states", label: "🇺🇸 EUA — Empresa (SEC EDGAR)", key: "business-united-states" },
			],
		},
		{
			type: "category",
			label: "Carteira de motorista",
			collapsible: false,
			items: [
				{ type: "doc", id: "driver-validation/chile-driver-license", label: "🇨🇱 Chile — Carteira de motorista" },
				{ type: "doc", id: "driver-validation/peru-driver-license", label: "🇵🇪 Peru — Carteira de motorista" },
				{ type: "doc", id: "driver-validation/florida-driver-license", label: "🇺🇸 Flórida (EUA) — Carteira de motorista" },
				{ type: "doc", id: "driver-validation/kansas-driver-license", label: "🇺🇸 Kansas (EUA) — Carteira de motorista" },
				{ type: "doc", id: "driver-validation/ontario-driver-license", label: "🇨🇦 Ontário — Carteira de motorista" },
			],
		},
		{
			type: "category",
			label: "Validação de veículos",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "🇦🇷 Argentina",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/argentina", label: "Visão geral", key: "vehicle-argentina-overview" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-vehicle-v3", label: "Veículo v3" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-traffic-infractions", label: "Buenos Aires - Infrações de trânsito" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-buenos-aires-technical-inspection", label: "Buenos Aires - Inspeção técnica" },
						{ type: "doc", id: "vehicle-validation/argentina/vehicle-validation-argentina-rto", label: "RTO" },
					],
				},
				{ type: "doc", id: "vehicle-validation/bolivia", label: "🇧🇴 Bolívia — Informações do veículo", key: "vehicle-bolivia" },
				{ type: "doc", id: "vehicle-validation/vehicle-validation-brazil", label: "🇧🇷 Brazil", key: "vehicle-brazil" },
				{ type: "doc", id: "vehicle-validation/chile", label: "🇨🇱 Chile — Veículo (placa)", key: "vehicle-chile" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-transport-vehicle", label: "🇨🇱 Chile — Transporte público", key: "vehicle-chile-transport-vehicle" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-technical-review", label: "🇨🇱 Chile — Revisão técnica", key: "vehicle-chile-vehicle-technical-review" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap", label: "🇨🇱 Chile — SOAP veicular", key: "vehicle-chile-vehicle-soap" },
				{ type: "doc", id: "vehicle-validation/chile/vehicle-validation-chile-vehicle-soap-plate", label: "🇨🇱 Chile — SOAP veicular (por placa)", key: "vehicle-chile-vehicle-soap-plate" },
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxes", label: "🇨🇴 Bogotá — imposto veículo" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-fines", label: "🇨🇴 Bogotá — multas de veículo" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-medellin-vehicle-fines", label: "🇨🇴 Medellín - Multas" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-vehicle-accidentality", label: "🇨🇴 Bogotá — acidentes" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-pico-y-placa", label: "🇨🇴 Bogotá — Pico y Placa" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-plate", label: "🇨🇴 Bogotá — táxi por placa" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-bogota-taxi-drivers-by-control-card", label: "🇨🇴 Bogotá - táxi por cartão de controle" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-values-by-plate", label: "🇨🇴 Fasecolda — valores por placa" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-vehicle-by-code", label: "🇨🇴 Fasecolda — valores por código" },
						{ type: "doc", id: "vehicle-validation/colombia/colombia-fasecolda-claims-verification", label: "🇨🇴 Fasecolda — sinistros" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-drivers-license", label: "🇨🇴 RUNT — CNH" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate", label: "🇨🇴 RUNT — veículo por placa (completo)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-plate-simplified", label: "🇨🇴 RUNT — veículo por placa (simplificado)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehiculo", label: "🇨🇴 RUNT — veículo (básico)" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-runt-vehicle-by-vin", label: "🇨🇴 RUNT — por VIN" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-fines", label: "🇨🇴 SIMIT - Multas" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-comparendo-details", label: "🇨🇴 SIMIT - Detalhes comparendo" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-agreements", label: "🇨🇴 SIMIT - Acordos de pagamento" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-resolutions", label: "🇨🇴 SIMIT - Resoluções" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-suspensiones", label: "🇨🇴 SIMIT — Suspensões" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-document", label: "🇨🇴 SIMIT - Consulta geral por documento de identificação" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-simit-general-query-by-plate", label: "🇨🇴 SIMIT - Consulta geral por placa" },
						{ type: "doc", id: "vehicle-validation/colombia/vehicle-validation-colombia-sisconmp-trainings", label: "🇨🇴 SISCONMP — formação (transporte)" },
					],
				},
				{ type: "doc", id: "vehicle-validation/costa-rica", label: "🇨🇷 Costa Rica — Veículo por placa", key: "vehicle-costa-rica" },
				{ type: "doc", id: "vehicle-validation/canada/ontario-plate", label: "🇨🇦 Canadá — Vencimento placa Ontário", key: "vehicle-canada-ontario-plate" },
				{ type: "doc", id: "vehicle-validation/ecuador", label: "🇪🇨 Equador — Multas de veículo", key: "vehicle-ecuador" },
				{ type: "doc", id: "vehicle-validation/paraguay", label: "🇵🇾 Paraguai — Informações do veículo", key: "vehicle-paraguay" },
				{ type: "doc", id: "vehicle-validation/spain", label: "🇪🇸 Espanha", key: "vehicle-spain" },
				{
					type: "category",
					label: "🇵🇪 Peru",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/peru", label: "🇵🇪 Peru — Veículos", key: "vehicle-peru-overview" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-information", label: "🇵🇪 Peru — Veículo por placa" },
						{ type: "doc", id: "vehicle-validation/peru/peru-vehicle-insurance", label: "🇵🇪 Peru — Seguro SOAT" },
					],
				},
				{
					type: "category",
					label: "🇺🇸 United States",
					collapsible: true,
					items: [
						{ type: "doc", id: "vehicle-validation/united-states/vehicle-by-vin", label: "Veículo por VIN", key: "vehicle-united-states" },
					],
				},
			],
		},
		{
			type: "category",
			label: "ANTECEDENTES",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 Brasil", key: "background-check-brazil" },
				{ type: "doc", id: "background-check/argentina-certificate-verify", label: "🇦🇷 Antecedentes criminais" },
				{ type: "doc", id: "background-check/chile-certificate-verify", label: "🇨🇱 Registro Civil" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 Contratos públicos" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC / medidas corretivas" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 Contraloria" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 Disciplinares (Procuradoria)" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
		{
			type: "category",
			label: "Certificados",
			collapsible: false,
			items: [
				{ type: "doc", id: "certificates/certificates-colombia-ministerio-trabajo-v3", label: "🇨🇴 Ministério do Trabalho (v3)" },
				{ type: "doc", id: "certificates/certificates-sena-certificates", label: "🇨🇴 Certificados SENA" },
			],
		},
		{
			type: "category",
			label: "VOTAÇÃO",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/voting", label: "🇨🇴 Colômbia — Local de votação (Registraduría)" },
				{ type: "doc", id: "legal/epic-eci", label: "🇮🇳 Índia — Consulta de nome EPIC (Voter ID)" },
				{ type: "doc", id: "legal/voting-eci-epic", label: "🇮🇳 Índia — Local de votação EPIC" },
			],
		},
		{
			type: "category",
			label: "RECURSOS",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "Validações de telefone",
					collapsible: true,
					items: [
						"resources/phone-validations/phone-validations",
						"resources/phone-validations/the-phone-validation-object",
						"resources/phone-validations/create-a-manual-phone-validation",
						"resources/phone-validations/create-a-phone-validation",
						"resources/phone-validations/retrieve-a-phone-validation",
						"resources/phone-validations/list-all-phone-validations",
						"resources/phone-validations/validate-a-phone-validation",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				{ type: "doc", id: "legal/privacy-policy", label: "legal/privacy-policy" },
				{ type: "doc", id: "legal/terms-and-conditions", label: "legal/terms-and-conditions" },
				{ type: "doc", id: "legal/service-level-agreement", label: "legal/service-level-agreement" },
				{ type: "doc", id: "legal/verifik-for-enterprises-hub-eng", label: "legal/verifik-for-enterprises-hub-eng" },
				{ type: "doc", id: "legal/smartcheck-terms-and-conditions-of-use", label: "legal/smartcheck-terms-and-conditions-of-use" },
			],
		},
	],
};

export default sidebars;
